-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE wos_case (
  wosc_id SERIAL NOT NULL,
  wosc_reference BYTEA NOT NULL,
  wosc_type BYTEA NOT NULL,
  wosc_central_id BIGINT NOT NULL,
  wosc_user_name BYTEA NOT NULL,
  wosc_subject BYTEA NOT NULL,
  wosc_summary TEXT DEFAULT NULL,
  wosc_status BYTEA NOT NULL,
  wosc_about TEXT DEFAULT NULL,
  wosc_category TEXT DEFAULT NULL,
  wosc_appeal TEXT DEFAULT NULL,
  wosc_filed TIMESTAMPTZ NOT NULL,
  wosc_updated TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(wosc_id)
);

CREATE UNIQUE INDEX wos_case_reference ON wos_case (wosc_reference);

CREATE INDEX wos_case_user ON wos_case (wosc_central_id, wosc_filed);


CREATE TABLE wos_comment (
  wosm_id SERIAL NOT NULL,
  wosm_case INT NOT NULL,
  wosm_portal_id INT DEFAULT NULL,
  wosm_author BYTEA NOT NULL,
  wosm_author_name BYTEA DEFAULT NULL,
  wosm_text TEXT NOT NULL,
  wosm_date TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(wosm_id)
);

CREATE UNIQUE INDEX wos_comment_portal ON wos_comment (wosm_case, wosm_portal_id);

CREATE INDEX wos_comment_case ON wos_comment (wosm_case, wosm_date);


CREATE TABLE wos_action (
  wosa_id SERIAL NOT NULL,
  wosa_reference BYTEA NOT NULL,
  wosa_central_id BIGINT NOT NULL,
  wosa_user_name BYTEA NOT NULL,
  wosa_type BYTEA NOT NULL,
  wosa_label BYTEA NOT NULL,
  wosa_scope BYTEA DEFAULT NULL,
  wosa_reason TEXT NOT NULL,
  wosa_issued TIMESTAMPTZ NOT NULL,
  wosa_expires TIMESTAMPTZ DEFAULT NULL,
  wosa_active SMALLINT DEFAULT 1 NOT NULL,
  wosa_appealable SMALLINT DEFAULT 1 NOT NULL,
  PRIMARY KEY(wosa_id)
);

CREATE UNIQUE INDEX wos_action_reference ON wos_action (wosa_reference);

CREATE INDEX wos_action_user ON wos_action (wosa_central_id, wosa_issued);


CREATE TABLE wos_standing (
  woss_user_name BYTEA NOT NULL,
  woss_central_id BIGINT DEFAULT NULL,
  woss_standing BYTEA NOT NULL,
  woss_banned SMALLINT DEFAULT 0 NOT NULL,
  woss_reference BYTEA DEFAULT NULL,
  woss_reason TEXT DEFAULT NULL,
  woss_expires TIMESTAMPTZ DEFAULT NULL,
  woss_appealable SMALLINT DEFAULT 1 NOT NULL,
  woss_updated TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(woss_user_name)
);

CREATE INDEX wos_standing_central ON wos_standing (woss_central_id);


CREATE TABLE wos_outbox (
  woso_id SERIAL NOT NULL,
  woso_wiki BYTEA NOT NULL,
  woso_action BYTEA NOT NULL,
  woso_payload TEXT NOT NULL,
  woso_attempts SMALLINT DEFAULT 0 NOT NULL,
  woso_created TIMESTAMPTZ NOT NULL,
  woso_next TIMESTAMPTZ DEFAULT NULL,
  woso_error TEXT DEFAULT NULL,
  PRIMARY KEY(woso_id)
);

CREATE INDEX wos_outbox_next ON wos_outbox (woso_next);
