-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wos_case (
  wosc_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  wosc_reference BLOB NOT NULL,
  wosc_type BLOB NOT NULL,
  wosc_central_id BIGINT UNSIGNED NOT NULL,
  wosc_user_name BLOB NOT NULL,
  wosc_subject BLOB NOT NULL,
  wosc_summary BLOB DEFAULT NULL,
  wosc_status BLOB NOT NULL,
  wosc_about BLOB DEFAULT NULL,
  wosc_category BLOB DEFAULT NULL,
  wosc_appeal BLOB DEFAULT NULL,
  wosc_filed BLOB NOT NULL,
  wosc_updated BLOB NOT NULL
);

CREATE UNIQUE INDEX wos_case_reference ON /*_*/wos_case (wosc_reference);

CREATE INDEX wos_case_user ON /*_*/wos_case (wosc_central_id, wosc_filed);


CREATE TABLE /*_*/wos_comment (
  wosm_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  wosm_case INTEGER UNSIGNED NOT NULL,
  wosm_portal_id INTEGER UNSIGNED DEFAULT NULL,
  wosm_author BLOB NOT NULL,
  wosm_author_name BLOB DEFAULT NULL,
  wosm_text BLOB NOT NULL,
  wosm_date BLOB NOT NULL
);

CREATE UNIQUE INDEX wos_comment_portal ON /*_*/wos_comment (wosm_case, wosm_portal_id);

CREATE INDEX wos_comment_case ON /*_*/wos_comment (wosm_case, wosm_date);


CREATE TABLE /*_*/wos_action (
  wosa_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  wosa_reference BLOB NOT NULL,
  wosa_central_id BIGINT UNSIGNED NOT NULL,
  wosa_user_name BLOB NOT NULL,
  wosa_type BLOB NOT NULL,
  wosa_label BLOB NOT NULL,
  wosa_scope BLOB DEFAULT NULL,
  wosa_reason BLOB NOT NULL,
  wosa_issued BLOB NOT NULL,
  wosa_expires BLOB DEFAULT NULL,
  wosa_active SMALLINT DEFAULT 1 NOT NULL,
  wosa_appealable SMALLINT DEFAULT 1 NOT NULL
);

CREATE UNIQUE INDEX wos_action_reference ON /*_*/wos_action (wosa_reference);

CREATE INDEX wos_action_user ON /*_*/wos_action (wosa_central_id, wosa_issued);


CREATE TABLE /*_*/wos_standing (
  woss_user_name BLOB NOT NULL,
  woss_central_id BIGINT UNSIGNED DEFAULT NULL,
  woss_standing BLOB NOT NULL,
  woss_banned SMALLINT DEFAULT 0 NOT NULL,
  woss_reference BLOB DEFAULT NULL,
  woss_reason BLOB DEFAULT NULL,
  woss_expires BLOB DEFAULT NULL,
  woss_appealable SMALLINT DEFAULT 1 NOT NULL,
  woss_updated BLOB NOT NULL,
  PRIMARY KEY(woss_user_name)
);

CREATE INDEX wos_standing_central ON /*_*/wos_standing (woss_central_id);


CREATE TABLE /*_*/wos_outbox (
  woso_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  woso_wiki BLOB NOT NULL,
  woso_action BLOB NOT NULL,
  woso_payload BLOB NOT NULL,
  woso_attempts SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
  woso_created BLOB NOT NULL,
  woso_next BLOB DEFAULT NULL,
  woso_error BLOB DEFAULT NULL
);

CREATE INDEX wos_outbox_next ON /*_*/wos_outbox (woso_next);
