-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wos_case (
  wosc_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  wosc_reference VARBINARY(32) NOT NULL,
  wosc_type VARBINARY(16) NOT NULL,
  wosc_central_id BIGINT UNSIGNED NOT NULL,
  wosc_user_name VARBINARY(255) NOT NULL,
  wosc_subject VARBINARY(255) NOT NULL,
  wosc_summary BLOB DEFAULT NULL,
  wosc_status VARBINARY(24) NOT NULL,
  wosc_about BLOB DEFAULT NULL,
  wosc_category BLOB DEFAULT NULL,
  wosc_appeal BLOB DEFAULT NULL,
  wosc_filed BINARY(14) NOT NULL,
  wosc_updated BINARY(14) NOT NULL,
  UNIQUE INDEX wos_case_reference (wosc_reference),
  INDEX wos_case_user (wosc_central_id, wosc_filed),
  PRIMARY KEY(wosc_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/wos_comment (
  wosm_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  wosm_case INT UNSIGNED NOT NULL,
  wosm_portal_id INT UNSIGNED DEFAULT NULL,
  wosm_author VARBINARY(16) NOT NULL,
  wosm_author_name VARBINARY(255) DEFAULT NULL,
  wosm_text BLOB NOT NULL,
  wosm_date BINARY(14) NOT NULL,
  UNIQUE INDEX wos_comment_portal (wosm_case, wosm_portal_id),
  INDEX wos_comment_case (wosm_case, wosm_date),
  PRIMARY KEY(wosm_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/wos_action (
  wosa_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  wosa_reference VARBINARY(32) NOT NULL,
  wosa_central_id BIGINT UNSIGNED NOT NULL,
  wosa_user_name VARBINARY(255) NOT NULL,
  wosa_type VARBINARY(32) NOT NULL,
  wosa_label VARBINARY(255) NOT NULL,
  wosa_scope VARBINARY(255) DEFAULT NULL,
  wosa_reason BLOB NOT NULL,
  wosa_issued BINARY(14) NOT NULL,
  wosa_expires BINARY(14) DEFAULT NULL,
  wosa_active TINYINT DEFAULT 1 NOT NULL,
  wosa_appealable TINYINT DEFAULT 1 NOT NULL,
  UNIQUE INDEX wos_action_reference (wosa_reference),
  INDEX wos_action_user (wosa_central_id, wosa_issued),
  PRIMARY KEY(wosa_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/wos_standing (
  woss_user_name VARBINARY(255) NOT NULL,
  woss_central_id BIGINT UNSIGNED DEFAULT NULL,
  woss_standing VARBINARY(32) NOT NULL,
  woss_banned TINYINT DEFAULT 0 NOT NULL,
  woss_reference VARBINARY(32) DEFAULT NULL,
  woss_reason BLOB DEFAULT NULL,
  woss_expires BINARY(14) DEFAULT NULL,
  woss_appealable TINYINT DEFAULT 1 NOT NULL,
  woss_updated BINARY(14) NOT NULL,
  INDEX wos_standing_central (woss_central_id),
  PRIMARY KEY(woss_user_name)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/wos_outbox (
  woso_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  woso_wiki VARBINARY(64) NOT NULL,
  woso_action VARBINARY(32) NOT NULL,
  woso_payload MEDIUMBLOB NOT NULL,
  woso_attempts SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
  woso_created BINARY(14) NOT NULL,
  woso_next BINARY(14) DEFAULT NULL,
  woso_error BLOB DEFAULT NULL,
  INDEX wos_outbox_next (woso_next),
  PRIMARY KEY(woso_id)
) /*$wgDBTableOptions*/;
